### ISSUE TITLE
error when adding Completions

### ISSUE THREAD

**Issue by chrisgrieser** [Rigellute/spotify-tui#1005]
First of all, thank you for this fantastic app!

I was trying to add completions for the CLI. The help page only mentions `spt --completions zsh`, so I assume you add completions just like with other CLIs by using `eval`. However, when I try to run that, I get:

```zsh
eval "$(spt --completions zsh)"
_arguments:comparguments:325: can only be called from completion function
```

I couldn't find any info in the readme or help page indicating that completions have to be added differently?

**Comment by OrangeFran** [comment]
Try adding the completions output to a location in your `$fpath`.
And the use `autoload -U compinit && compinit` to load the completions.

**Comment by henderjm** [comment]
just because it was also my first time consuming bash completions like this. I created a new folder in my home directory .bash_autocompletions/ and added it to my $fpath.

I then put the output into a file and most importantly name it the same as the executable and prefix it with an underscore! Don't be dumb and call it spotify-tui 
```sh
mkdir ~/.bash_autocompletions.d
spt --completions zsh > ~/.bash_autocompletions/_spt
```

add to your bash dotfile in my case .zshrc
```
fpath=(~/.bash_completion.d/ $fpath)
autoload -U compinit && compinit
```
refresh and you should see it working as expected.

**Comment by chrisgrieser** [comment]
Right, that was actually it, forgot to close the issue afterwards.
