### ISSUE TITLE
No prompt redirect URL in terminal during setup

### ISSUE THREAD

**Issue by stiansenandreas** [Rigellute/spotify-tui#169]
After linking me to the authorization site and then being redirected I don't see any new prompts in the terminal setup to paste the redirect URL:

Opened https://accounts.spotify.com/authorize?client_id=......&redirect_uri=http:%2F%2Flocalhost:8888%2Fcallback&scope=playlist-read-collaborative%20playlist-read-private%20user-follow-read%20user-library-modify%20user-library-read%20user-modify-playback-state%20user-read-currently-playing%20user-read-playback-state%20user-read-private%20user-read-recently-played& in your browser

And then nothing.

**Comment by Rigellute** [comment]
Sounds like the auto redirect logic is failing. Could be because your running `spotify-tui` via ssh/on a different machine?

What should happen is that when you enter your client credentials, a localhost server is setup and listens for the redirect_uri request to do that step automatically. If your broswer is running on a different machine, the `spotify-tui` server will just wait forever (needs to be fixed using a timeout to fallback to manual entry).

Have a look at [this issue](https://github.com/Rigellute/spotify-tui/issues/136#issuecomment-549771256) to see if it's the same problem you're having.

There is also a workaround for you to try.

**Comment by stiansenandreas** [comment]
Well this is embarrasing, there was a missing character in my hosts file causing localhost not to be recognized, works fine now. I'm on a local desktop but thank you for pointing me in the right direction with networking related issues.

**Comment by Rigellute** [comment]
Thanks @stiansenandreas 👌
