### ISSUE TITLE
Saving tracks with `s` doesn't appear to work

### ISSUE THREAD

**Issue by alichtman** [Rigellute/spotify-tui#18]
```
$ spt --version
spotify-tui 0.4.0
```

**Comment by baxtea** [comment]
Right now the keybind is written to save hovered songs, not the currently playing song, and only in the recently-played list and in album listings. That seems to be intentional and functional, but it's not very user-friendly imo.

With a preface that I am tired and likely have not thought this through all the way, my pitch is the now-playing bar becomes its own hoverable element. The keybind is active there to save the current song when it's hovered. Making it selectable could also provide a reasonably cohesive solution to #16 . Since the now-playing bar takes the entire width of the terminal, left and right arrows could be specialized to scrub when it's selected, with Ctrl+left/right and Ctrl+up/down used globally for skipping and volume, respectively.

**Comment by Rigellute** [comment]
Thanks for this.

As @baxtea says, I've only implemented saving a track within the Recently Played view and with the album view.

Not only do I need to add this to the other views, but also implement removing saved tracks and showing that track is liked/saved.

I like the idea of making the playbar hoverable, with its own event handlers for saving the currently playing track, viewing track info etc.

**Comment by Rigellute** [comment]
PR making the the playbar hoverable https://github.com/Rigellute/spotify-tui/pull/80

**Comment by Rigellute** [comment]
Saving tracks is implemented in every view now. And you can save the currently playing track by hovering on the playbar and pressing `s`

**Comment by stigok** [comment]
For me this is toggling shuffle.

**Comment by stigok** [comment]
Now it worked! I had bound it to shuffle in my `config.yml`. Sorry! Thanks for a great app :)

**Comment by blueForestIcarus** [comment]
saving works for me in the song view for regular album/playlists , but not when I have discover weekly open, then "s" doesn't do anything

**Comment by ericonr** [comment]
@blueForestIcarus 

> As baxtea says, I've only implemented saving a track within the Recently Played view and with the album view.
> Not only do I need to add this to the other views, but also implement removing saved tracks and showing that track is liked/saved.

You can probably open a new issue for it, to track the implementation.
