### ISSUE TITLE
"Daily Mix" playlists missing

### ISSUE THREAD

**Issue by zsolt-donca** [Rigellute/spotify-tui#401]
When using the web client or the official desktop client, I have several "Daily Mix" playlists, from 1 to 6 at the moment. However, when using spotify-tui, I only have "Daily Mix 1" under the "Playlists" section. Is there something I can do to make all these auto-generated "Daily Mix" playlists appear? Thank you.

**Comment by TimotheeGerber** [comment]
Unfortunately, it seems that there is no way to get the "Daily Mix" playlists from the official Spotify API. I had a look and didn't find any endpoint for it. So, `spotify-tui` won't be able to automatically fetch these playlist for everyone. 

However, you can add these playlists to your library (click on the heart or the three dots + add to library) in the official Spotify client or the web client. Then, they should be accessible from the playlists section of `spotify-tui`. Note that I don't know if there are still dynamic once pinned. I hope so.

**Comment by TimotheeGerber** [comment]
Finally, there won't be a PR. The trick used in `made_for_you_search_and_add` function is only working when the "Daily Mix X" playlist is already in the user library (it was the case for me, that's why I fought it was possible). If it is not the case, the spotify-owned playlist will no be in the first results of the search API call and won't be added to the `Made for you` section of `spotify-tui`.

I am sorry for the false hope about automatically fetching those playlists. It is still possible to add them to your library to see them in `spotify-tui`. And I checked the [Spotify documentation](https://support.spotify.com/uk/using_spotify/playlists/made-for-you-playlists/): even when saved, the daily mix are still regularly refreshed!

**Comment by zsolt-donca** [comment]
Thank you for your follow-up! I can confirm that clicking on the heart for all my "Daily Mix" lists does make them appear under the "Playlists" section. This is a great workaround! It could be worth adding it under a FAQ section or something.

However, the "Daily mixes" don't appear for me under the "Made For You" section; I have only the following there:
- Discover Weekly
- Release Radar
- On Repeat
- Repeat Rewind

Should they appear here? I don't entirely understand.

**Comment by TimotheeGerber** [comment]
No, they should not appear in the "Made for you" section. Only in the "Playlists" section.

I tried to automatically add them in the "Made for you" section but failed due to the limited Spotify API and its inconsistent search results.

Sorry if my previous post was confusing. I gave some technical information about what I tried in case someone wants to tackle this issue too.

**Comment by zsolt-donca** [comment]
Thank you for the clarification! I think we can close this issue.

**Comment by Rigellute** [comment]
Thanks for the investigation efforts here, greatly appreciated 👍
