### ISSUE TITLE
Open playlists by url?

### ISSUE THREAD

**Issue by jedahan** [Rigellute/spotify-tui#41]
Would love to know if I am listening to the correct playlist when a friend shares one, such as https://open.spotify.com/playlist/0LbHaoYiD4HCZrrHsf5JK5?si=LlvBb9ySSDmNqzuH4qhRiw

**Comment by jedahan** [comment]
I would like to be able to enter the url and jump to the playlist!

If this is a good first contribution it would be cool to label it so :)

**Comment by Rigellute** [comment]
This is a tricky one, but certainly do able.

We need to 
1. Update the 'enter' (`'\n'`) event in the input handler to check if input is a url, if so parse the url to extract the type (playlist) and id
1. Fetch the playlist
1. Push the playlist view onto the navigation stack

Might not be a great first issue, but please feel free to have a crack at it!

**Comment by Utagai** [comment]
I'll take a crack at this soon because this is one of the ways I would actually use the Spotify desktop client sometimes. I would just put the Spotify URI or share link of whatever a friend shared into the search box to find it.

I think though that this issue can be generalized to any Spotify share link or Spotify URI, since it should also be able to work for albums, tracks, etc, including playlists.

Plus, it _should_ be doable for both URIs and share links.
