### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by securitybreach** [Rigellute/spotify-tui#476]
On Archlinux using chrome or firefox, I get the following  error:

INVALID_CLIENT: Invalid redirect URI

![2020-05-24-111240_2535x379_scrot](https://user-images.githubusercontent.com/263925/82758963-4fc50f00-9dd9-11ea-9848-1ba8439e005a.png)

**Comment by tomyrobichaud** [comment]
Did you add the callback URI on your app on the spotify dev dashboard?

**Comment by securitybreach** [comment]
I did not, I will do that now. I just installed the application and the redirect when I opened it gave that error message.

**Comment by tomyrobichaud** [comment]
You might have figured it out by now but here are the instructions from the README:

## Connecting to Spotify’s API

`spotify-tui` needs to connect to Spotify’s API in order to find music by
name, play tracks etc.

Instructions on how to set this up will be shown when you first run the app.

But here they are again:

1. Go to the [Spotify dashboard](https://developer.spotify.com/dashboard/applications)
1. Click `Create a Client ID` and create an app
1. Now click `Edit Settings`
1. Add `http://localhost:8888/callback` to the Redirect URIs
1. You are now ready to authenticate with Spotify!
1. Go back to the terminal
1. Run `spt`
1. Enter your `Client ID`
1. Enter your `Client Secret`
1. You will be redirected to an official Spotify webpage to ask you for permissions.
1. After accepting the permissions, you'll be redirected to localhost. If all goes well, the redirect URL will be parsed automatically and now you're done. If the local webserver fails for some reason you'll be redirected to a blank webpage that might say something like "Connection Refused" since no server is running. Regardless, copy the URL and paste into the prompt in the terminal.

And now you are ready to use the `spotify-tui` 🎉

You can edit the config at anytime at `${HOME}/.config/spotify-tui/client.yml`.

**Comment by securitybreach** [comment]
Thanks
