### ISSUE TITLE
Artist field is missing from album view

### ISSUE THREAD

**Issue by bdemirel** [Rigellute/spotify-tui#488]
From what I can see, this issue only happens when I view an album through the albums list on the library sidebar. The title bar of the table shows #, title, artist and length, but the content of the table doesn't have any artist, instead shows the length in artist column, leaving the last column empty. However, if I view the same albums through the artist's page, or from the search results, everything is fine.

**Comment by sputnick1124** [comment]
It seems that when we open up an album table [from the Library context](https://github.com/Rigellute/spotify-tui/blob/master/src/handlers/album_list.rs#L42-L53), we are given a [`Full`](https://github.com/Rigellute/spotify-tui/blob/master/src/handlers/album_list.rs#L49) `AlbumTableContext`, instead of a `Simplified` one.

The `Full` context view [does not show album artists](https://github.com/Rigellute/spotify-tui/blob/master/src/ui/mod.rs#L568-L569), for some reason, but the `Simplified` one [does](https://github.com/Rigellute/spotify-tui/blob/master/src/ui/mod.rs#L542)

**Comment by Rigellute** [comment]
Huh... good debugging @sputnick1124, thank you.

**Comment by sputnick1124** [comment]
I looked very briefly into and started formulating a fix, but only had a few minutes before I had to put it down. After that initial poke, I admit this totally dropped out of my consciousness.

I can take a look at it sometime this week/weekend, if needed.
