### ISSUE TITLE
SoundCloud support

### ISSUE THREAD

**Issue by sumanthratna** [Rigellute/spotify-tui#524]
It would be nice if I could use SoundCloud with this (I completely understand if you don't want to do this). I think the only changes would need to occur in [`src/network.rs`](https://github.com/Rigellute/spotify-tui/blob/9648083bdb37237b70020a7044d4490a06af9067/src/network.rs) (I think we could just turn network into a folder and add two files inside of it: `spotify.rs` and `soundcloud.ts`).

- https://crates.io/crates/soundcloud
- https://crates.io/crates/soundcloud-fs
- https://github.com/Rigellute/spotify-tui#roadmap

**Comment by Rigellute** [comment]
Nice idea though I think this will be out of scope for spotify-tui. All the current state management would need to change due to the types being different. 

Perhaps an abstraction could be created that would handle spotify, soundcloud, apple music etc. APIs. 

However I think it'd be best for a new application to be made that could handle this.
