### ISSUE TITLE
Why can't free accounts use spotify-tui

### ISSUE THREAD

**Issue by Titaniumtown** [Rigellute/spotify-tui#561]
Is there any way for free accounts to use spotify-tui? Futhermore, why does spotify-tui rely on a api-key, and not just reproducing how the official client interacts with the spotify servers.

**Comment by Rigellute** [comment]
spotify-tui uses the [Spotify Web API](https://developer.spotify.com/documentation/web-api/). To do anything useful (like controlling playback) requires authentication - with the additional constraint that the user has a premium account. This is part of the terms of service of Spotify. 

And because spotify-tui is a client application (i.e. does not run on a server), the best user experience requires us to create an individual client id.

[spotifyd](https://github.com/Spotifyd/spotifyd) more closely mimics the official client, but doesn't have a tui like spotify-tui

**Comment by berkemir** [comment]
I logged in with my other account which has not premium. How can I log in with another account? I deleted the config file which is in .config/spotify-tui. I also reinstalled the spotify-tui but both of them didn't worked.
