### ISSUE TITLE
Not detecting spotifyd (works intermittently)

### ISSUE THREAD

**Issue by IanQS** [Rigellute/spotify-tui#618]
Firstly, thank you so so much for making this! On my system (Arch Linux x64) Spotify is a resource hog and this was a godsend. 

Do you know why my spotifyd is only detected intermittently? I've done the standard "turn program off and on again" but nothing works. It works every time I start my computer up again but at random points it stops working. I've checked my `spotifyd` via 

`systemctl status spotifyd.service`

and receive back

```
● spotifyd.service - A spotify playing daemon
     Loaded: loaded (/etc/systemd/system/spotifyd.service; enabled; vendor preset: disabled)
     Active: active (running) since Fri 2020-10-09 09:51:14 PDT; 2 days ago
       Docs: https://github.com/Spotifyd/spotifyd
   Main PID: 558938 (spotifyd)
      Tasks: 2 (limit: 19032)
     Memory: 2.4M
     CGroup: /system.slice/spotifyd.service
             └─558938 /usr/bin/spotifyd --no-daemon

Oct 09 09:51:14 ian-pc systemd[1]: Started A spotify playing daemon.
Oct 09 09:51:14 ian-pc spotifyd[558938]: No config file specified. Running with default values
Oct 09 09:51:14 ian-pc spotifyd[558938]: No proxy specified
Oct 09 09:51:14 ian-pc spotifyd[558938]: Using software volume controller.
```

---

P.S: the logging URL seems to be broken
```
# Using with spotifyd

Follow the spotifyd documentation to get set up.

After that there is not much to it.

    Start running the spotifyd daemon.
    Start up spt
    Press d to go to the device selection menu and the spotifyd "device" should be there - if not check these docs
```

The "if not check these docs" URL seems to be broken/ doesn't lead me to the logging section

**Comment by Utagai** [comment]
I've ran into this problem, also on Arch. I've found success by restarting `spotifyd`, but it's not a solution:
```
systemctl --user restart spotifyd
```

This is likely not an `spt` problem though, since restarting `spt` doesn't do anything but restarting `spotifyd` _does_. I seem to only get this problem when I wake my laptop up from suspend, I have a feeling that `spotifyd` is messing something up there, but I haven't looked into it very deeply. It's quite hard to reproduce because, like you said, it's seemingly intermittent.

**Comment by Utagai** [comment]
Sorry for the double post, but my best guess at the moment is that software that registers itself as a device to the spotify API must maintain an open connection to the spotify API at all times. This is how Spotify can say things, in real-time, about what's playing and what devices are "online".

My guess is that `spotifyd` is dropping that connection on suspend, and isn't properly re-establishing a connection to Spotify. I know for example that my laptop takes a solid 15-20 seconds to re-connect to my wifi on wake, so I wonder if we are just exceeding some connection timeout, since I doubt `spotifyd` would forget something so fundamental as a reconnect.

That said, I haven't looked into things yet. I plan to in the future, but it's not one of my main priorities at the moment with my `spt` + `spotifyd` set-up.

**Comment by IanQS** [comment]
Ahh, thanks, it worked! I'll wait to hear back from @Rigellute to see if I should open an issue on `spotifyd`. I'll make sure to tag you in it and link to this URL too.

> know for example that my laptop takes a solid 15-20 seconds to re-connect to my wifi on wake, so I wonder if we are just exceeding some connection timeout, since I doubt spotifyd would forget something so fundamental as a reconnect.

Unfortunately, I'm on a wired connection so maybe that isn't the reason :p

**Comment by IanQS** [comment]
I may or may not have found something? I listened via Spotifyd on my machine then went to another device to listen on there. When I came back it wasn't working / detecting Spotifyd anymore. I'll run a few tests in the morning

**Comment by Utagai** [comment]
@IanQS Glad that it helped you out! For now, I just restart `spotifyd` and it's quick enough of a band-aid "fix" that it hasn't gotten on my nerves, _yet_.

Definitely tag me. I'm pretty sure I'll be looking into this eventually. The tip on listening to Spotify on another device seems useful if its a consistent reproduction.

**Comment by Rigellute** [comment]
Thanks everyone. This does sound like an issue with spotifyd rather than spotify-tui. We use a simple call to the `devices` endpoint to find available devices - there's no fancy local discovery going on

**Comment by Davincible** [comment]
@Rigellute I also have this discovery issue, but not only with spotifyd, also with local devices. The 'native' electron spotify app detects all devices, including spotifyd and local devices on the network, but spotifytui only detects spotifyd when I restart it, and no network devices
