### ISSUE TITLE
Update to new version

### ISSUE THREAD

**Issue by Ciavarella** [Rigellute/spotify-tui#62]
First of all, i have tried your tui now for a while and i gotta say that i love it! I follow every new feature and i am really happy to see all the progress.

Sorry if this is not the right forum but do you have a command that updates the tui to the latest version? Or should this command check the latest version when it starts?

Example: I have the older version that does not have "next track". Could it be a good thing to implement a check for your latest version so i know that i could update it? I have to check everything manually now.

Solution: Check if the user has the latest version and ask if you want to update. When new update is installed maybe have some text with new implemented features?

**Comment by Rigellute** [comment]
Thank you, I greatly appreciate it.

Regarding updates, my current workflow is to build up some unreleased features and then I manually create a release for both `brew` and `cargo`.

You can then update with these commands

#### macOS
```sh
brew upgrade spotify-tui
```
#### linux
```
cargo update spotify-tui
```

I plan to manage the versions through these package managers, rather than implementing an autoupdating feature. 

Perhaps one day we will achieve continous development - on every merge to `master` a new release is auto created.

I also like your idea of showing the release notes when you start up `spt`, I will explore that!

**Comment by Rigellute** [comment]
Also, if you want to stay on the bleeding edge, you can clone this repo and run in development mode.

You can [follow these instructions](https://github.com/Rigellute/spotify-tui#development) to get setup.

**Comment by Ciavarella** [comment]
Great! Sorry for being unclear there for a moment, i know how to upgrade but i just thought that it would be nice to have an autoupdating feature but the `brew upgrade spotify-tui` command works fine to!

Regarding release notes i think that would be awsome!

Again, great work! Very impressive!
