### ISSUE TITLE
Navigation in search input can go out of bounds

### ISSUE THREAD

**Issue by synth-ruiner** [Rigellute/spotify-tui#63]
To replicate, type something into the search box and keep pressing the left arrow key- you can keep going past the first character and overflow off to the right side of the screen. the program usually crashes after other input at this point.

Home and end keys don't work either, but I can forgive that. :)

Installed via cargo on Thursday 10 Oct so apologies if this has been fixed since then.

This program is really awesome- thanks a lot! I'm using it to control the office spotify machine without having to get up ;)

**Comment by Rigellute** [comment]
Oh good spot!

I know what the issue is, will create a PR to fix a bit later. 

And thank you for your kind feedback.

p.s. if you want to jump to the start and end of the input (like what "Home" and "End" do) you can use `<Ctrl-a>` to jump to start and `<Ctrl-e>` to jump to the end (this is inteded to be in keeping with standard terminal keybinds).

**Comment by Rigellute** [comment]
PR fixing this here https://github.com/Rigellute/spotify-tui/pull/64
