### ISSUE TITLE
error 500 select device 

### ISSUE THREAD

**Issue by x0rld** [Rigellute/spotify-tui#813]
I've configured spotifyd with my creds and I have a premium account but when I select my device I have a code 500 from the API
![image](https://user-images.githubusercontent.com/45242856/117968714-c75fb700-b326-11eb-907c-4d4cd68e8a56.png)

**Comment by Weriel** [comment]
What worked for me was to start playing a song in the Spotify-Client and then selecting the device. There was also a second Device in the "Connect to a device" menu in Spotify itself named after my PC. Might wanna check that. 
Keep in mind that I am using the standard Spotify client for this and not spotifyd or anything like that.

Regarding the second point, I sadly cannot replicate this anymore otherwise I would add a screenshot of that.
